### ISSUE TITLE
`chardet` dependency not in your Pipfile

### ISSUE THREAD

**Issue by a-berg** [Madoshakalaka/pipenv-setup#73] opened 2021-09-21 07:25 UTC
I have tried to install `pipenv-setup` as shown in your README (`pipenv install --dev pipenv-setup`).
When using sync (`pipenv run pipenv-setup sync`) I get the message `ModuleNotFoundError: No module named 'chardet'`. Your Pipfile doesn't contain it as far as I can tell, so I had to `pipenv install --dev chardet`.
Is this intended? It seems like a bug to me.

**Comment by nomis** [comment] 2021-10-05 08:06
This is caused by a missing dependency in https://github.com/sarugaku/requirementslib/issues/296.

**Comment by bryant-finney** [comment] 2021-11-07 00:48
@a-berg and @nomis 

This issue has been resolved by PR #76 ; release [v3.1.2](https://github.com/Madoshakalaka/pipenv-setup/releases/tag/v3.1.2) patches this dependency and is available on [![PyPI version](https://badge.fury.io/py/pipenv-setup.svg)](https://badge.fury.io/py/pipenv-setup) 🙂

**Closed by bryant-finney** 2021-11-07 00:48 UTC
